import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :ns_web, NsWeb.Endpoint,
  url: [host: "nseguin.dev"],
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: 4000],
  https: [
    port: 4040,
    cipher_suite: :strong,
    otp_app: :ns_web,
    keyfile: System.get_env("SSL_KEY_PATH"),
    certfile: System.get_env("SSL_CERT_PATH"),
    cacertfile: System.get_env("SSL_CA_CERT_PATH"),
    force_ssl: [rewrite_on: [:x_forwarded_host, :x_forwarded_proto]]
  ]

# Configures Swoosh API Client
config :swoosh, :api_client, Ns.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :plug_content_security_policy,
  nonces_for: [:script_src, :style_src],
  report_only: false,
  directives: %{
    default_src: ~w('self'),
    connect_src: ~w('self'),
    child_src: ~w('self'),
    img_src: ~w('self' data:),
    script_src: ~w('strict-dynamic' 'self' 'unsafe-eval' 'unsafe-inline'),
    style_src: ~w('self'),
    frame_ancestors: [
      "'self'",
      "http://nsegu.in",
      "https://nsegu.in",
      "https://nseguin.dev"
    ]
  }
