name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict

      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles(format('{0}/mix.lock', github.workspace)) }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: npm

      - run: make prepare
      - run: make build push
